# Generated by Django 3.1.7 on 2022-06-04 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220604_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='post_office',
            new_name='post_office_or_shop',
        ),
    ]
