# Generated by Django 4.0.5 on 2022-06-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_algorith_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category1',
        ),
        migrations.RenameModel(
            old_name='Brand',
            new_name='Category2',
        ),
        migrations.RenameModel(
            old_name='Algorith',
            new_name='Category3',
        ),
        migrations.AlterModelOptions(
            name='category1',
            options={'verbose_name_plural': 'categories1'},
        ),
        migrations.AlterModelOptions(
            name='category2',
            options={'verbose_name_plural': 'categories2'},
        ),
        migrations.AlterModelOptions(
            name='category3',
            options={'verbose_name_plural': 'categories3'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='category2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='algorith_or_models',
            new_name='category3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
