# Generated by Django 3.1.7 on 2022-06-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoptions',
            name='delivery_street',
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(choices=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')], help_text='Required', max_length=255, verbose_name='delivery_method'),
        ),
    ]
