# Generated by Django 4.0.5 on 2022-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shop', models.CharField(db_index=True, max_length=255)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
    ]
